# Generated by Django 5.0.7 on 2024-08-10 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_owner_billing_app', '0001_initial'),
        ('shop_owner_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_owner_registration_app.shop_owner_registration_model')),
            ],
        ),
    ]
