# Generated by Django 5.0.7 on 2024-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_owner_billing_app', '0003_producttransaction_product_buying_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='product_buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
