# Generated by Django 5.0.7 on 2024-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_owner_billing_app', '0004_alter_producttransaction_product_buying_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
