# Generated by Django 5.0.7 on 2024-08-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_owner_billing_app', '0005_customerpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchase',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
