# Generated by Django 5.0.7 on 2024-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_owner_billing_app', '0006_alter_customerpurchase_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=150)),
            ],
        ),
    ]
