# Generated by Django 5.0.7 on 2024-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_owner_billing_app', '0007_phonenumbersearchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpurchase',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
