# Generated by Django 5.0.7 on 2024-07-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop_owner_registration_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_owner_first_name', models.CharField(max_length=250, null=True)),
                ('shop_owner_last_name', models.CharField(max_length=250, null=True)),
                ('shop_owner_shop_name', models.CharField(max_length=250, null=True, unique=True)),
                ('shop_owner_mail_id', models.EmailField(max_length=254, null=True, unique=True)),
                ('shop_owner_phone_number', models.IntegerField(max_length=10, null=True, unique=True)),
                ('shop_owner_street_address', models.CharField(max_length=1500, null=True)),
                ('shop_owner_village_name', models.CharField(max_length=1500, null=True)),
                ('shop_owner_mandal_name', models.CharField(max_length=1500, null=True)),
                ('shop_owner_city_name', models.CharField(max_length=1500, null=True)),
                ('shop_owner_state_name', models.CharField(max_length=1500, null=True)),
                ('shop_owner_pincode', models.IntegerField(max_length=10, null=True)),
                ('shop_owner_password', models.CharField(max_length=50, null=True)),
                ('shop_owner_confirm_password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
