# Generated by Django 5.0.7 on 2024-08-03 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_registration_app', '0001_initial'),
        ('shop_owner_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_owner_registration_app.shop_owner_registration_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_registration_app.customer_registration_model')),
            ],
        ),
    ]
