# Generated by Django 5.0.7 on 2024-07-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_owner_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_owner_add_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, null=True)),
                ('product_buying_price', models.IntegerField(null=True)),
                ('product_selling_price', models.IntegerField(null=True)),
                ('product_qunatity', models.IntegerField(null=True)),
                ('product_storage_place', models.CharField(max_length=50, null=True)),
                ('shop_user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_owner_registration_app.shop_owner_registration_model')),
            ],
        ),
    ]
