# Generated by Django 5.0.7 on 2024-07-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_registration_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=100, null=True)),
                ('customer_last_name', models.CharField(max_length=150, null=True)),
                ('customer_mail_id', models.EmailField(max_length=254, null=True)),
                ('customer_phone_number', models.IntegerField(max_length=10, null=True)),
                ('customer_password', models.CharField(max_length=50, null=True)),
                ('customer_confirm_password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
